name: Run Tests

on:
  push:
    paths:
      - '**.py'                  # déclenche si fichiers .py changent
      - 'requirements.txt'       # déclenche si requirements.txt change
      - '.github/workflows/**'   # déclenche si un fichier workflow change
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
